alias ChainsparkApi.Repo
alias ChainsparkApi.Tokens
alias ChainsparkApi.Tokens.Token
alias ChainsparkApi.Accounts.User
alias ChainsparkApi.Jobs.TokenPrices
alias ChainsparkApi.Jobs.TokenHolders
alias ChainsparkApi.Jobs.TokenHoldersCrawler
alias ChainsparkApi.Wallets
alias ChainsparkApi.Entities
alias ChainsparkApi.Entities.Entity
